apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<github-username>/argocd-example-apps' # Update to match your fork.
    path: helm-guestbook
    targetRevision: HEAD
  destination:
    namespace: helm-guestbook
    name: <environment-name> # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
