---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
      - env: qa
      - env: prod
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: env
              operator: In
              values:
                - dev
          #maxUpdate: 100%  # if undefined, all applications matched are updated together (default is 100%)
        - matchExpressions:
            - key: env
              operator: In
              values:
                - qa
          # maxUpdate: 0      # if 0, no matched applications will be updated
        - matchExpressions:
            - key: env
              operator: In
              values:
                - prod
          # maxUpdate: 10%    # maxUpdate supports both integer and percentage string values (rounds down, but floored at 1 Application for >0%)
  goTemplate: true
  template:
    metadata:
      name: 'helm-guestbook-{{.env}}'
      labels:
        env: '{{.env}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/argoproj/argocd-example-apps.git
          path: helm-guestbook
          targetRevision: master
          helm:
            valueFiles:
            - $values/helm-guestbook-values/values-{{.env}}.yaml
            values: |
              image:
                tag: 0.2
        - ref: values
          repoURL: https://github.com/morey-tech/argocd-example-apps.git
          targetRevision: v2.6.0-rc
      destination:
        name: 'in-cluster'
        namespace: '{{.env}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true