apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      path: helm-guestbook
      targetRevision: HEAD
      helm:
        valueFiles:
        - $values/charts/prometheus/values.yaml
    - ref: values
      repoURL: https://github.com/morey-tech/argocd-example-apps.git
      path: helm-guestbook-values
      targetRevision: v2.6.0-rc