apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/argoproj/argocd-example-apps.git
      path: helm-guestbook
      targetRevision: master
      helm:
        valueFiles:
        - $values/helm-guestbook-values/values-dev.yaml
    - ref: values
      repoURL: https://github.com/morey-tech/argocd-example-apps.git
      targetRevision: v2.6.0-rc