apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/crenshaw-dev/plugin-test-app.git
    path: .
    plugin:
      env:
        - name: FOO
          value: bar
        - name: REV
          value: test-$ARGOCD_APP_REVISION
      parameters:
        - name: array-param
          array:
            - override
            - values
  destination:
    namespace: default
    server: https://kubernetes.default.svc