apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/argocd-example-apps.git'
    path: argo-cd
    targetRevision: v2.6.0-rc
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd